version: "2"
services:
  ui:
    restart: always
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - service
    volumes:
      - ./client/:/usr/src/app/client
      - /usr/src/app/client/node_modules
    command: npm start
  service:
    build: ./server
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./server:/server
      - /server/node_modules
    command: >
      /bin/bash -c "
        apt-get update && apt-get install -y netcat
        while ! nc -z mongo 27017;
        do
          echo waiting for mongodb server;
          sleep 1;
        done;
        echo Connected!;
        npm start
      "
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017