version: "2"
services:
  ui:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - service
    links:
      - service
    command: >
      /bin/bash -c "
        npm start
      "
  service:
    image: treecalcservice_app:latest
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    command: >
      /bin/bash -c "
        apt-get update && apt-get install -y netcat
        while ! nc -z mongo 27017;
        do
          echo waiting for mongodb server;
          sleep 1;
        done;
        echo Connected!;
        npm start
      "
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"